name: Build and Deploy

env:
  APP_LOCATION: "site"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13      
          cache: 'pip' # caching pip dependencies
      - run: pip install mkdocs-material 
      - run: pip install --user -r requirements.txt
      - run: mkdir -p config/en
      - run: cp template/mkdocs.template config/en/mkdocs.yml
      - run: sed -i -e 's/LANG/en/g' config/en/mkdocs.yml
      - run: bash template/generate-nav-tree.sh docs/en config/en/mkdocs.yml
      - run: mkdocs build -f config/en/mkdocs.yml
      - run: cp docs/index.html site/
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

  spellcheck:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/
      - name: Run Vale spellcheck
        uses: vale-cli/vale-action@v2
        with:
          files: docs/en
          reporter: github-pr-review
          fail_on_error: true
          vale_flags: "--config .vale/.vale.ini"

  deploy:
    needs: 
      - build
      - spellcheck
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          skip_app_build: true
          skip_api_build: true
